// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package dbpostgres

import (
	"encoding/json"
	"time"
)

type AppExercise struct {
	ExerciseID   int64  `db:"exercise_id" json:"exerciseId"`
	ExerciseName string `db:"exercise_name" json:"exerciseName"`
}

type AppImage struct {
	ImageID     int64  `db:"image_id" json:"imageId"`
	UserID      int64  `db:"user_id" json:"userId"`
	ContentType string `db:"content_type" json:"contentType"`
	ImageData   []byte `db:"image_data" json:"imageData"`
}

type AppSet struct {
	SetID      int64 `db:"set_id" json:"setId"`
	ExerciseID int64 `db:"exercise_id" json:"exerciseId"`
	Weight     int32 `db:"weight" json:"weight"`
}

type AppUser struct {
	UserID       int64           `db:"user_id" json:"userId"`
	UserName     string          `db:"user_name" json:"userName"`
	PassWordHash string          `db:"pass_word_hash" json:"passWordHash"`
	Name         string          `db:"name" json:"name"`
	Config       json.RawMessage `db:"config" json:"config"`
	CreatedAt    time.Time       `db:"created_at" json:"createdAt"`
	IsEnabled    bool            `db:"is_enabled" json:"isEnabled"`
}

type AppWorkout struct {
	WorkoutID int64     `db:"workout_id" json:"workoutId"`
	UserID    int64     `db:"user_id" json:"userId"`
	SetID     int64     `db:"set_id" json:"setId"`
	StartDate time.Time `db:"start_date" json:"startDate"`
}
